openapi: 3.2.0
info:
  title: Quandoo Public Partner Reservation Enquiries API
  description: The Quandoo Public Partner API is a multi-purpose REST API for the Quandoo restaurant reservations platform.
  version: 1.0.0
  contact:
    name: Quandoo Developers
    email: developers@quandoo.com
    url: https://docs.quandoo.com/
servers:
- url: https://public-api.prod.quandoo.com
  description: Production
security:
- API_TOKEN: []
tags:
- name: Reservation Enquiries
paths:
  /v1/reservation-enquiries:
    put:
      tags:
      - Reservation Enquiries
      summary: Quandoo Create Reservation Enquiries
      operationId: createReservationEnquiry_1
      description: This endpoint allows to create a reservation enquiry for a certain capacity, start and end time.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MerchantReservationEnquiryData'
            examples:
              CreateReservationEnquiry1RequestExample:
                summary: Default createReservationEnquiry_1 request
                x-microcks-default: true
                value:
                  reservationEnquiry:
                    id: '88086'
                    merchantId: 88086
                    capacity: 4
                    startDateTime: '2026-07-15T19:30:00'
                    endDateTime: '2026-07-15T19:30:00'
                    message: Window table preferred if available.
                  customer:
                    id: '88086'
                    firstName: Jane
                    lastName: Smith
                    emailAddress: jane.smith@example.com
                    phoneNumber: 030120765890
                    locale: de_DE
                    country: DE
                    subscriptions:
                    - {}
                  tracking:
                    agent: {}
                    cookie: {}
        description: Reservation enquiry data
      responses:
        '200':
          description: Reservation enquiry successfully created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreatedReservationEnquiryData'
              examples:
                CreateReservationEnquiry1200Example:
                  summary: Default createReservationEnquiry_1 200 response
                  x-microcks-default: true
                  value:
                    reservationEnquiry:
                      id: '88086'
                    customer:
                      id: '88086'
                    links:
                    - href: {}
                      method: {}
                      rel: {}
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                CreateReservationEnquiry1400Example:
                  summary: Default createReservationEnquiry_1 400 response
                  x-microcks-default: true
                  value:
                    errorType: BAD_REQUEST_ERROR
                    errorMessage: Window table preferred if available.
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                CreateReservationEnquiry1500Example:
                  summary: Default createReservationEnquiry_1 500 response
                  x-microcks-default: true
                  value:
                    errorType: BAD_REQUEST_ERROR
                    errorMessage: Window table preferred if available.
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
  /v1/reservation-enquiries/{reservationEnquiryId}:
    get:
      tags:
      - Reservation Enquiries
      summary: Quandoo Get Reservation Enquiry by Id
      operationId: getReservationEnquiry_1
      description: 'This endpoint allows an agent to get an reservation enquiry by id. The id is agent-specific. The agent needs to be authenticated.


        The endpoint will return `HTTP 404 - Not Found` if the reservation enquiry with the specified id could not be found.


        It will return `HTTP 403 - Forbidden` if the agent is not authenticated, if the agent doesn''t have permissions or the reservation enquiry doesn''t belong to the authenticated agent.


        ####Request:

        * **reservationEnquiryId**: Agent-specific ID of the requested reservation enquiry


        ####Response:

        * **id**: The agent-dependent unique id of the reservation enquiry

        * **merchantId**: The ID of the merchant at which this reservation enquiry was made

        * **customerId**: The ID of the customer to which this reservation enquiry belongs

        * **capacity**: The capacity (people count) of the reservation enquiry

        * **startDateTime**: The start date time of the reservation enquiry. Format: yyyy-MM-ddTHH:mm:ssZ

        * **endDateTime**: The end date time of the reservation enquiry. Format: yyyy-MM-ddTHH:mm:ssZ

        * **status**: The status of the reservation enquiry which can be one of: NEW, IN_PROGRESS, ACCEPTED or REJECTED


        Example curl:

        ```

        curl https://{host}/v{X}/reservation-enquiries/07f53b36-3f48-11e5-a151-feff819cdc9f

        ```


        Example response:

        ```

        {

        "id": "07f53b36-3f48-11e5-a151-feff819cdc9f",

        "merchantId": 1384,

        "customerId": "35fff464-142c-48ac-a0c6-ed72a1615664",

        "capacity": 4,

        "startTime": "2015-06-22T12:00:00+00:00",

        "endTime": "2015-06-22T13:00:00+00:00",

        "status": "NEW"

        }

        ```'
      parameters:
      - name: reservationEnquiryId
        in: path
        required: true
        description: Id of the reservation enquiry
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetReservationEnquiryData'
              examples:
                GetReservationEnquiry1200Example:
                  summary: Default getReservationEnquiry_1 200 response
                  x-microcks-default: true
                  value:
                    id: '88086'
                    merchantId: 88086
                    customerId: '88086'
                    capacity: 4
                    startDateTime: '2026-07-15T19:30:00'
                    endDateTime: '2026-07-15T19:30:00'
                    status: CONFIRMED
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                GetReservationEnquiry1400Example:
                  summary: Default getReservationEnquiry_1 400 response
                  x-microcks-default: true
                  value:
                    errorType: BAD_REQUEST_ERROR
                    errorMessage: Window table preferred if available.
        '403':
          description: Access denied
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                GetReservationEnquiry1403Example:
                  summary: Default getReservationEnquiry_1 403 response
                  x-microcks-default: true
                  value:
                    errorType: BAD_REQUEST_ERROR
                    errorMessage: Window table preferred if available.
        '404':
          description: Reservation enquiry not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                GetReservationEnquiry1404Example:
                  summary: Default getReservationEnquiry_1 404 response
                  x-microcks-default: true
                  value:
                    errorType: BAD_REQUEST_ERROR
                    errorMessage: Window table preferred if available.
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                GetReservationEnquiry1500Example:
                  summary: Default getReservationEnquiry_1 500 response
                  x-microcks-default: true
                  value:
                    errorType: BAD_REQUEST_ERROR
                    errorMessage: Window table preferred if available.
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
    patch:
      tags:
      - Reservation Enquiries
      summary: Quandoo Update Status of Reservation Enquiry by Id
      operationId: updateReservationEnquiry_1
      description: 'This endpoint allows to update the status of a reservation enquiry with the given ID. The allowed status transitions are as following:


        * NEW --> IN_PROGRESS --> {ACCEPTED/REJECTED}

        * ACCEPTED REJECTED


        The endpoint will return `HTTP 404 - Not Found` if the reservation enquiry with the specified id could not be found.


        The endpoint will return `HTTP 400 - Bad Request` if the specified status is wrong.


        The endpoint will return `HTTP 409 - Conflict` if the status change is invalid.


        The endpoint will return `HTTP 403 - Forbidden` if the agent is not authenticated, if the agent doesn''t have permissions or the reservation enquiry

        doesn''t belong to the authenticated agent.


        ####Request:

        * **reservationEnquiryId**: Agent-specific ID of the requested reservation enquiry

        * **reservationEnquiryData**: The new enquiry status'
      parameters:
      - name: reservationEnquiryId
        in: path
        required: true
        description: Id of the reservation enquiry
        schema:
          type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateReservationEnquiryData'
            examples:
              UpdateReservationEnquiry1RequestExample:
                summary: Default updateReservationEnquiry_1 request
                x-microcks-default: true
                value:
                  status: CONFIRMED
        description: New reservation enquiry status
      responses:
        '200':
          description: OK
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                UpdateReservationEnquiry1400Example:
                  summary: Default updateReservationEnquiry_1 400 response
                  x-microcks-default: true
                  value:
                    errorType: BAD_REQUEST_ERROR
                    errorMessage: Window table preferred if available.
        '403':
          description: Access denied
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                UpdateReservationEnquiry1403Example:
                  summary: Default updateReservationEnquiry_1 403 response
                  x-microcks-default: true
                  value:
                    errorType: BAD_REQUEST_ERROR
                    errorMessage: Window table preferred if available.
        '404':
          description: Invalid reservation enquiry status transition
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                UpdateReservationEnquiry1404Example:
                  summary: Default updateReservationEnquiry_1 404 response
                  x-microcks-default: true
                  value:
                    errorType: BAD_REQUEST_ERROR
                    errorMessage: Window table preferred if available.
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                UpdateReservationEnquiry1500Example:
                  summary: Default updateReservationEnquiry_1 500 response
                  x-microcks-default: true
                  value:
                    errorType: BAD_REQUEST_ERROR
                    errorMessage: Window table preferred if available.
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
  /v1/reservation-enquiries/{reservationEnquiryId}/messages:
    get:
      tags:
      - Reservation Enquiries
      summary: Quandoo Get All Messages of a Reservation Enquiry
      operationId: getMessagesForReservationEnquiry_1
      description: 'This endpoint allows an agent to get all messages of a reservation enquiry. The id of the reservation enquiry is agent-specific. The agent needs to be authenticated.


        The endpoint will return `HTTP 404 - Not Found` if the reservation enquiry with the specified id could not be found.


        It will return `HTTP 403 - Forbidden` if the agent is not authenticated, if the agent doesn''t have permissions or the reservation enquiry doesn''t belong to the authenticated agent.


        ####Request:

        * **reservationEnquiryId**: Agent-specific ID of the requested reservation enquiry


        ####Response:

        The response will contain a _list_ of messages. Each one containing the following fields:

        * **senderType**: If this message was sent by the customer or by the merchant

        * **creationDate**: The date time that this message was created. Format: yyyy-MM-ddTHH:mm:ssZ

        * **message**: The text of the message itself.


        Example curl:

        ```

        curl https://{host}/v{X}/reservation-enquiries/07f53b36-3f48-11e5-a151-feff819cdc9f/messages

        ```


        Example response:

        ```

        {

        "messages": [

        {

        "senderType": "CUSTOMER",

        "message": "Customer specific message",

        "creationDate": "2018-05-04T09:26:53Z"

        }

        ]

        }

        ```'
      parameters:
      - name: reservationEnquiryId
        in: path
        required: true
        description: Id of the reservation enquiry
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReservationEnquiryMessageList'
              examples:
                GetMessagesForReservationEnquiry1200Example:
                  summary: Default getMessagesForReservationEnquiry_1 200 response
                  x-microcks-default: true
                  value:
                    messages:
                    - senderType: {}
                      message: {}
                      creationDate: {}
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                GetMessagesForReservationEnquiry1400Example:
                  summary: Default getMessagesForReservationEnquiry_1 400 response
                  x-microcks-default: true
                  value:
                    errorType: BAD_REQUEST_ERROR
                    errorMessage: Window table preferred if available.
        '403':
          description: Access denied
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                GetMessagesForReservationEnquiry1403Example:
                  summary: Default getMessagesForReservationEnquiry_1 403 response
                  x-microcks-default: true
                  value:
                    errorType: BAD_REQUEST_ERROR
                    errorMessage: Window table preferred if available.
        '404':
          description: Reservation enquiry not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                GetMessagesForReservationEnquiry1404Example:
                  summary: Default getMessagesForReservationEnquiry_1 404 response
                  x-microcks-default: true
                  value:
                    errorType: BAD_REQUEST_ERROR
                    errorMessage: Window table preferred if available.
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                GetMessagesForReservationEnquiry1500Example:
                  summary: Default getMessagesForReservationEnquiry_1 500 response
                  x-microcks-default: true
                  value:
                    errorType: BAD_REQUEST_ERROR
                    errorMessage: Window table preferred if available.
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
components:
  schemas:
    LinkRelationDto:
      type: object
      properties:
        href:
          type: string
          format: url
          example: https://www.quandoo.com/place/sample-restaurant
        method:
          type: string
          example: string
        rel:
          type: string
          enum:
          - DETAILS
          - WIDGET
          - WIDGET_DETAILS
          - GET_MERCHANT
          - PARENT
          - SELF
          - SETTINGS
          - AVAILABILITY_DAYS
          - AVAILABILITIES
          - CREATE_RESERVATION
          - GET_RESERVATION
          - UPDATE_RESERVATION
          - GET_CUSTOMER_RESERVATION
          - GET_REVIEW
          - PORTAL_PREORDER_FORM
          - RESERVATION_CHECKOUT_PAGE
          - CREDIT_CARD_DETAILS_PAGE
          - CUSTOMER_EDIT_RESERVATION
          example: DETAILS
    MerchantCustomer:
      type: object
      required:
      - country
      - locale
      - phoneNumber
      properties:
        id:
          type: string
          description: Identifier of the customer for the calling agent. (Agent dependent field)
          example: '88086'
        firstName:
          type: string
          description: The first name of the customer. Optional.
          example: Jane
        lastName:
          type: string
          description: The last name of the customer.
          example: Smith
        emailAddress:
          type: string
          description: The email address of the customer.
          example: jane.smith@example.com
        phoneNumber:
          type: string
          description: The phone number of the customer. The expected format is E164 e.g. +4930120765890
          example: 030120765890
        locale:
          type: string
          description: The locale of the customer. E.g. de_DE
          example: de_DE
        country:
          type: string
          description: The 2 letter ISO country of the customer, e.g. DE
          example: DE
        subscriptions:
          type: array
          description: The requested subscriptions, e.g. QUANDOO, MERCHANT
          items:
            $ref: '#/components/schemas/MerchantSubscription'
    ReservationEnquiryMessageList:
      type: object
      properties:
        messages:
          type: array
          items:
            $ref: '#/components/schemas/ReservationEnquiryMessageData'
    UpdateReservationEnquiryData:
      type: object
      properties:
        status:
          type: string
          description: The status of the reservation enquiry
          example: CONFIRMED
    ReservationEnquiryMessageData:
      type: object
      properties:
        senderType:
          type: string
          enum:
          - MERCHANT
          - CUSTOMER
          example: MERCHANT
        message:
          type: string
          example: Window table preferred if available.
        creationDate:
          type: string
          format: date-time
          description: 'The date the review created on. Format: yyyy-MM-ddTHH:mm:ssZ'
          example: '2026-07-15T19:30:00'
    AgentTracking:
      type: object
      required:
      - id
      properties:
        id:
          type: integer
          format: int32
          description: An agent id. Required.
          example: 1
    MerchantReservationEnquiry:
      type: object
      required:
      - capacity
      - endDateTime
      - id
      - merchantId
      - message
      - startDateTime
      properties:
        id:
          type: string
          description: The unique identifier of the reservation enquiry for the calling agent (Agent dependent field) or NULL if the agent identifier should be created. Optional.
          example: '88086'
        merchantId:
          type: integer
          format: int32
          description: The ID of the merchant at which this reservation will be made.
          example: 88086
        capacity:
          type: integer
          format: int32
          description: The capacity (people count) of the reservation enquiry.
          minimum: 1
          example: 4
        startDateTime:
          type: string
          description: 'The start date and time of the potential reservation. Format: yyyy-MM-ddTHH:mm:ssZ'
          example: '2026-07-15T19:30:00'
        endDateTime:
          type: string
          description: 'The end date and time of the potential reservation. Format: yyyy-MM-ddTHH:mm:ssZ'
          example: '2026-07-15T19:30:00'
        message:
          type: string
          description: A message from the customer.
          minLength: 0
          maxLength: 5000
          example: Window table preferred if available.
    MerchantReservationEnquiryData:
      type: object
      required:
      - customer
      - reservationEnquiry
      - tracking
      properties:
        reservationEnquiry:
          description: The reservation enquiry data.
          $ref: '#/components/schemas/MerchantReservationEnquiry'
        customer:
          description: The customer data.
          $ref: '#/components/schemas/MerchantCustomer'
        tracking:
          description: The tracking data.
          $ref: '#/components/schemas/Tracking'
    CreatedReservationEnquiry:
      type: object
      required:
      - id
      properties:
        id:
          type: string
          description: The identifier of the reservation enquiry for the calling agent (Agent-dependent field)
          example: '88086'
    RestCookie:
      type: object
      properties:
        tracking:
          type: string
          description: A tracking string to be stored with the reservation. Optional.
          example: string
        referenceId:
          type: string
          description: A reference id to be stored with the reservation. Optional.
          example: '88086'
    ErrorResponse:
      type: object
      properties:
        errorType:
          type: string
          enum:
          - BAD_REQUEST_ERROR
          - FORBIDDEN_ERROR
          - NOT_FOUND_ERROR
          - METHOD_NOT_ALLOWED_ERROR
          - NOT_ACCEPTABLE_ERROR
          - UNSUPPORTED_MEDIA_TYPE_ERROR
          - START_TIME_NOT_FOUND_ERROR
          - MERCHANT_ID_INVALID
          - RESERVATION_CAPACITY_MISSING
          - RESERVATION_CAPACITY_INVALID
          - RESERVATION_DATE_TIME_MISSING
          - RESERVATION_DATE_TIME_INVALID_FORMAT
          - RESERVATION_EXTRA_INFO_INVALID
          - RESERVATION_SHOW_POSTCODE
          - RESERVATION_DATE_TIME_INVALID_IN_THE_PAST
          - RESERVATION_NO_TABLES_AVAILABLE
          - RESERVATION_NOT_FOUND
          - RESERVATION_IN_NON_EDITABLE_STATUS
          - RESERVATION_WITH_SMART_OFFER_EDIT
          - RESERVATION_WITH_CCV_EDIT
          - RESERVATION_IOVOX_OFFER_EDIT
          - RESERVATION_WITH_PREPAID_MENU_EDIT
          - RESERVATION_FOR_MERCHANT_WITH_FEEDBACK_TIME
          - RESERVATION_WALKIN_NOT_EDITABLE
          - RESERVATION_CUSTOMER_CANNOT_EDIT
          - RESERVATION_PROMO_CODE_PARAM_INVALID
          - RESERVATION_PROMO_CODE_NOT_FOUND
          - RESERVATION_PROMO_CODE_INVALID_DESTINATION
          - RESERVATION_PROMO_CODE_ALREADY_USED
          - RESERVATION_PROMO_CODE_INVALID_CAMPAIGN
          - RESERVATION_PROMO_CODE_DATE_TIME_IN_PAST_OR_FUTURE
          - RESERVATION_PROMO_CODE_INVALID_DAY_OF_WEEK
          - RESERVATION_PROMO_CODE_INVALID_AGENT
          - RESERVATION_PROMO_CODE_INVALID_MERCHANT
          - RESERVATION_PROMO_CODE_INVALID_PARTNER_VOUCHER
          - RESERVATION_PROMO_CODE_ALREADY_OWNED_BY_CUSTOMER
          - RESERVATION_INVITATION_PROMO_CODE_NOT_FIRST_RESERVATION
          - CCV_SETTINGS_REQUIRED
          - CCV_CARD_REQUIRED
          - CCV_SETTINGS_INVALID
          - CCV_SETTINGS_OFFLINE
          - CCV_CARD_INVALID
          - ENQUIRY_INVALID_MIN_COVERS
          - CUSTOMER_FIRST_NAME_INVALID
          - CUSTOMER_LAST_NAME_MISSING
          - CUSTOMER_LAST_NAME_INVALID
          - CUSTOMER_EMAIL_MISSING
          - CUSTOMER_EMAIL_INVALID
          - CUSTOMER_NEWSLETTER_REQUESTED_MISSING
          - CUSTOMER_PHONE_NUMBER_MISSING
          - CUSTOMER_COUNTRY_INVALID
          - CUSTOMER_ID_EXISTS
          - CUSTOMER_PHONE_NUMBER_INVALID
          - UNEXPECTED_SERVER_ERROR
          - PHONE_NUMBER_MISSING
          - PHONE_NUMBER_INVALID
          - UUID_CONFLICT
          - RESERVATION_STATUS_CONFLICT
          - INVALID_RESERVATION_GUESTS_QUANTITY
          - MENU_MAPPING_FAILED
          example: BAD_REQUEST_ERROR
        errorMessage:
          type: string
          example: Window table preferred if available.
    GetReservationEnquiryData:
      type: object
      required:
      - customerId
      properties:
        id:
          type: string
          description: The agent-dependent unique id of the reservation enquiry
          example: '88086'
        merchantId:
          type: integer
          format: int32
          description: The ID of the merchant at which this reservation enquiry was made
          example: 88086
        customerId:
          type: string
          description: The ID of the customer to which this reservation enquiry belongs
          example: '88086'
        capacity:
          type: integer
          format: int32
          description: The capacity (people count) of the reservation enquiry
          example: 4
        startDateTime:
          type: string
          description: 'The start date time of the reservation enquiry. Format: yyyy-MM-ddTHH:mm:ssZ'
          example: '2026-07-15T19:30:00'
        endDateTime:
          type: string
          description: 'The end date time of the reservation enquiry. Format: yyyy-MM-ddTHH:mm:ssZ'
          example: '2026-07-15T19:30:00'
        status:
          type: string
          description: 'The status of the reservation enquiry which can be one of:  NEW, IN_PROGRESS, ACCEPTED or REJECTED'
          example: CONFIRMED
    Tracking:
      type: object
      required:
      - agent
      properties:
        agent:
          description: The id of the agent creating this request and partner references if any. Required.
          $ref: '#/components/schemas/AgentTracking'
        cookie:
          description: Cookie information to be stored with this reservation. Optional.
          $ref: '#/components/schemas/RestCookie'
    MerchantSubscription:
      type: object
      properties:
        id:
          type: string
          enum:
          - QUANDOO
          - MERCHANT
          example: QUANDOO
    CreatedCustomer:
      type: object
      required:
      - id
      properties:
        id:
          type: string
          description: The id of the customer for the calling agent. (Agent dependent field)
          example: '88086'
    CreatedReservationEnquiryData:
      type: object
      required:
      - customer
      - links
      - reservationEnquiry
      properties:
        reservationEnquiry:
          description: The object holding the reservation enquiry data.
          $ref: '#/components/schemas/CreatedReservationEnquiry'
        customer:
          description: The object holding the customer data.
          $ref: '#/components/schemas/CreatedCustomer'
        links:
          type: array
          description: Related links to follow
          items:
            $ref: '#/components/schemas/LinkRelationDto'
  securitySchemes:
    API_TOKEN:
      type: apiKey
      name: X-Quandoo-AuthToken
      in: header
