openapi: 3.2.0
info:
  title: Quandoo Public Partner Reviews API
  description: The Quandoo Public Partner API is a multi-purpose REST API for the Quandoo restaurant reservations platform.
  version: 1.0.0
  contact:
    name: Quandoo Developers
    email: developers@quandoo.com
    url: https://docs.quandoo.com/
servers:
- url: https://public-api.prod.quandoo.com
  description: Production
security:
- API_TOKEN: []
tags:
- name: Reviews
paths:
  /v1/reviews:
    get:
      tags:
      - Reviews
      summary: Quandoo Get Information from Reviews in a List
      operationId: getReviews_2
      description: This resource return a list of reviews.
      parameters:
      - name: merchantId
        in: query
        required: false
        description: MerchantId to get the reviews from. Cannot be used in combination with 'reservationId'
        schema:
          type: integer
          format: int32
      - name: reservationId
        in: query
        required: false
        description: Reservation id to get the reviews from. Either public id or agent reference id. Cannot be used in combination with 'merchantId'. When set, 'offset' and 'limit' are ignored. All reviews for a reservation are returned.
        schema:
          type: string
      - name: offset
        in: query
        required: false
        description: Skip first n reviews
        schema:
          type: integer
          format: int32
          default: 0
      - name: limit
        in: query
        required: false
        description: Max number to retrieve
        schema:
          type: integer
          format: int32
          default: 10
      responses:
        '200':
          description: Review response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetReviewsDto'
              examples:
                GetReviews2200Example:
                  summary: Default getReviews_2 200 response
                  x-microcks-default: true
                  value:
                    reviews:
                    - reviewId: {}
                      merchantId: {}
                      customer: {}
                      status: {}
                      locale: {}
                      rating: {}
                      description: {}
                      reservationId: {}
                      createdAt: {}
                    size: 1
                    offset: 1
                    limit: 1
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                GetReviews2400Example:
                  summary: Default getReviews_2 400 response
                  x-microcks-default: true
                  value:
                    errorType: BAD_REQUEST_ERROR
                    errorMessage: Window table preferred if available.
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                GetReviews2500Example:
                  summary: Default getReviews_2 500 response
                  x-microcks-default: true
                  value:
                    errorType: BAD_REQUEST_ERROR
                    errorMessage: Window table preferred if available.
        '404':
          description: Review not found error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                GetReviews2404Example:
                  summary: Default getReviews_2 404 response
                  x-microcks-default: true
                  value:
                    errorType: BAD_REQUEST_ERROR
                    errorMessage: Window table preferred if available.
        '403':
          description: Access denied
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                GetReviews2403Example:
                  summary: Default getReviews_2 403 response
                  x-microcks-default: true
                  value:
                    errorType: BAD_REQUEST_ERROR
                    errorMessage: Window table preferred if available.
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
    put:
      tags:
      - Reviews
      summary: Quandoo Create a Review for a Reservation
      operationId: createReview_1
      description: 'This resource manages the creation of reviews for a particular agent and a reservation. Reviews must have a description, rating and a reservation public identifier or agent specific reference identifier with reservation agent identifier. The agent must be the one that created the reservation, otherwise it is forbidden.


        ####Request:

        The request needs to have 3 parameters for review reviewId, description and rating.


        * **reservationId**: Public ID or agent specific reference id of the reservation where to add a review. **Required**.

        * **description**: Text content of the review to be set. Optional. A review requires a minimum of a rating.

        * **rating**: Integer value from 1 to 6 with the new rating given. **Required**.


        ####Response:

        The response is a review object containing information about the review.


        * **reviewId**: The Id of the created review.

        * **status**: Status of the created review. Can be ''CREATED'', ''PUBLISHED'' or ''DENIED''. After a successful creation, ''CREATED'' is returned.

        * **links**: A series of links where to get details of the created review;


        Example curl:

        ```

        curl -H "Content-Type: application/json" -X PUT https://{host}/v{X}/reviews/ -d ''

        {

        "reservationId": "07f53b36-3f48-11e5-a151-feff819cdc9f",

        "description": "Some description of the review",

        "rating": 1

        }

        ```


        ```

        curl -H "Content-Type: application/json" -X PUT https://{host}/v{X}/reviews/ -d ''

        {

        "reservationId": "1111112",

        "description": "Some description of the review",

        "rating": 1,

        }

        ```


        Example response:

        ```

        {

        "reviewId": "01a53b36-3f48-11e5-a151-feff819cdc9f",

        "status": "CREATED",

        "links": [{

        "href": "http://localhost:39250/v1/reviews/01a53b36-3f48-11e5-a151-feff819cdc9f",

        "method": "GET",

        "rel": "get-review"

        }]

        }

        ```'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateReviewDto'
            examples:
              CreateReview1RequestExample:
                summary: Default createReview_1 request
                x-microcks-default: true
                value:
                  reservationId: '88086'
                  rating: 1
                  description: Window table preferred if available.
        description: Review for this reservation
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChangedReviewDto'
              examples:
                CreateReview1200Example:
                  summary: Default createReview_1 200 response
                  x-microcks-default: true
                  value:
                    reviewId: '88086'
                    status: AVAILABLE_TO_REVIEW
                    links:
                    - href: {}
                      method: {}
                      rel: {}
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                CreateReview1400Example:
                  summary: Default createReview_1 400 response
                  x-microcks-default: true
                  value:
                    errorType: BAD_REQUEST_ERROR
                    errorMessage: Window table preferred if available.
        '403':
          description: Access denied
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                CreateReview1403Example:
                  summary: Default createReview_1 403 response
                  x-microcks-default: true
                  value:
                    errorType: BAD_REQUEST_ERROR
                    errorMessage: Window table preferred if available.
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                CreateReview1500Example:
                  summary: Default createReview_1 500 response
                  x-microcks-default: true
                  value:
                    errorType: BAD_REQUEST_ERROR
                    errorMessage: Window table preferred if available.
        '404':
          description: Reservation not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                CreateReview1404Example:
                  summary: Default createReview_1 404 response
                  x-microcks-default: true
                  value:
                    errorType: BAD_REQUEST_ERROR
                    errorMessage: Window table preferred if available.
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
    patch:
      tags:
      - Reviews
      summary: Quandoo Updated a Review
      operationId: updateReview_1
      description: 'This resource manages the update of reviews for a given review ID. Description and rating can be updated on a review. The agent must be the one that owns the reservation associated to the review to modify, otherwise a forbidden response is returned.


        **NOTE**: Reviews in state ''PUBLISHED'' or ''DENIED'' cannot be updated. Only those in status ''CREATED'' are allowed to be updated.


        ####Request:

        The request needs to have 3 parameters for reservation reviewId (public reviewId), description and rating.


        * **reviewId**: Id of the review. **Required**.

        * **description**: Text content of the review. If not set (null value) it won''t be considered for update.

        * **rating**: Integer value from 1 to 6 with the rating given. If not set (null value) it won''t be considered for update.


        In case both description and rating are set to null, nothing happens to the review: it is not updated and its state remains.


        ####Response:

        The response is a review object containing information about the review.


        * **reviewId**: The Id of the updated review.

        * **status**: Status of the updated review. Can be ''CREATED'', ''PUBLISHED'' or ''DENIED''. Upon a successful update, the status ''CREATED'' is returned.

        * **links**: A series of links where to get details of the updated review.


        Example curl:

        ```

        curl -H "Content-Type: application/json" -X PATCH https://{host}/v{X}/reviews/ -d ''

        {

        "reviewId": "01a53b36-3f48-11e5-a151-feff819cdc9f",

        "description": "Some updated description for the review",

        "rating": 2

        }

        ```


        Example response:

        ```

        {

        "reviewId": "01a53b36-3f48-11e5-a151-feff819cdc9f",

        "status": "CREATED",

        "links": [{

        "href": "http://localhost:39250/v1/reviews/01a53b36-3f48-11e5-a151-feff819cdc9f",

        "method": "GET",

        "rel": "get-review"

        }]

        }

        ```'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateReviewDto'
            examples:
              UpdateReview1RequestExample:
                summary: Default updateReview_1 request
                x-microcks-default: true
                value:
                  reviewId: '88086'
                  rating: 1
                  description: Window table preferred if available.
        description: Review for this reservation
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChangedReviewDto'
              examples:
                UpdateReview1200Example:
                  summary: Default updateReview_1 200 response
                  x-microcks-default: true
                  value:
                    reviewId: '88086'
                    status: AVAILABLE_TO_REVIEW
                    links:
                    - href: {}
                      method: {}
                      rel: {}
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                UpdateReview1400Example:
                  summary: Default updateReview_1 400 response
                  x-microcks-default: true
                  value:
                    errorType: BAD_REQUEST_ERROR
                    errorMessage: Window table preferred if available.
        '403':
          description: Access denied
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                UpdateReview1403Example:
                  summary: Default updateReview_1 403 response
                  x-microcks-default: true
                  value:
                    errorType: BAD_REQUEST_ERROR
                    errorMessage: Window table preferred if available.
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                UpdateReview1500Example:
                  summary: Default updateReview_1 500 response
                  x-microcks-default: true
                  value:
                    errorType: BAD_REQUEST_ERROR
                    errorMessage: Window table preferred if available.
        '404':
          description: Reservation not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                UpdateReview1404Example:
                  summary: Default updateReview_1 404 response
                  x-microcks-default: true
                  value:
                    errorType: BAD_REQUEST_ERROR
                    errorMessage: Window table preferred if available.
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
components:
  schemas:
    UpdateReviewDto:
      type: object
      required:
      - reviewId
      properties:
        reviewId:
          type: string
          format: uuid
          description: UUID identifying the review.
          example: '88086'
        rating:
          type: integer
          format: int32
          description: 'Rating associated to this review. Possible values: 1 to 6.'
          example: 1
        description:
          type: string
          description: Description associated to this review.
          example: Window table preferred if available.
    LinkRelationDto:
      type: object
      properties:
        href:
          type: string
          format: url
          example: https://www.quandoo.com/place/sample-restaurant
        method:
          type: string
          example: string
        rel:
          type: string
          enum:
          - DETAILS
          - WIDGET
          - WIDGET_DETAILS
          - GET_MERCHANT
          - PARENT
          - SELF
          - SETTINGS
          - AVAILABILITY_DAYS
          - AVAILABILITIES
          - CREATE_RESERVATION
          - GET_RESERVATION
          - UPDATE_RESERVATION
          - GET_CUSTOMER_RESERVATION
          - GET_REVIEW
          - PORTAL_PREORDER_FORM
          - RESERVATION_CHECKOUT_PAGE
          - CREDIT_CARD_DETAILS_PAGE
          - CUSTOMER_EDIT_RESERVATION
          example: DETAILS
    GetReviewsDto:
      type: object
      properties:
        reviews:
          type: array
          description: List of returned reviews.
          items:
            $ref: '#/components/schemas/GetReviewDto'
        size:
          type: integer
          format: int32
          description: Number of reviews returned in this object.
          example: 1
        offset:
          type: integer
          format: int32
          description: Offset to apply on the next pagination request. Can be higher than the number of available reviews.
          example: 1
        limit:
          type: integer
          format: int32
          description: Expected number of reviews that could be retrieved in the next pagination request. Can actually be less than the number returned. Its value is 0 when it is sure there are no more reviews available for pagination using the 'offset' as starting point.
          example: 1
    ChangedReviewDto:
      type: object
      required:
      - links
      - reviewId
      properties:
        reviewId:
          type: string
          format: uuid
          description: Id of to the review.
          example: '88086'
        status:
          type: string
          description: The status of the change.
          enum:
          - AVAILABLE_TO_REVIEW
          - CREATED
          - DENIED
          - PUBLISHED
          example: AVAILABLE_TO_REVIEW
        links:
          type: array
          description: The links related to this entity.
          items:
            $ref: '#/components/schemas/LinkRelationDto'
    CustomerReviewData:
      type: object
      properties:
        identifier:
          type: string
          description: Identifier of the customer associated to this review. Only in detailed view.
          example: string
        firstName:
          type: string
          description: Customer first name associated to this review. Only in detailed view.
          example: Jane
        lastName:
          type: string
          description: First letter of customer last name associated to this review. Only in detailed view.
          example: Smith
        profileImage:
          type: string
          description: Customer profile image URL associated to this review. Only in detailed view.
          example: string
    ErrorResponse:
      type: object
      properties:
        errorType:
          type: string
          enum:
          - BAD_REQUEST_ERROR
          - FORBIDDEN_ERROR
          - NOT_FOUND_ERROR
          - METHOD_NOT_ALLOWED_ERROR
          - NOT_ACCEPTABLE_ERROR
          - UNSUPPORTED_MEDIA_TYPE_ERROR
          - START_TIME_NOT_FOUND_ERROR
          - MERCHANT_ID_INVALID
          - RESERVATION_CAPACITY_MISSING
          - RESERVATION_CAPACITY_INVALID
          - RESERVATION_DATE_TIME_MISSING
          - RESERVATION_DATE_TIME_INVALID_FORMAT
          - RESERVATION_EXTRA_INFO_INVALID
          - RESERVATION_SHOW_POSTCODE
          - RESERVATION_DATE_TIME_INVALID_IN_THE_PAST
          - RESERVATION_NO_TABLES_AVAILABLE
          - RESERVATION_NOT_FOUND
          - RESERVATION_IN_NON_EDITABLE_STATUS
          - RESERVATION_WITH_SMART_OFFER_EDIT
          - RESERVATION_WITH_CCV_EDIT
          - RESERVATION_IOVOX_OFFER_EDIT
          - RESERVATION_WITH_PREPAID_MENU_EDIT
          - RESERVATION_FOR_MERCHANT_WITH_FEEDBACK_TIME
          - RESERVATION_WALKIN_NOT_EDITABLE
          - RESERVATION_CUSTOMER_CANNOT_EDIT
          - RESERVATION_PROMO_CODE_PARAM_INVALID
          - RESERVATION_PROMO_CODE_NOT_FOUND
          - RESERVATION_PROMO_CODE_INVALID_DESTINATION
          - RESERVATION_PROMO_CODE_ALREADY_USED
          - RESERVATION_PROMO_CODE_INVALID_CAMPAIGN
          - RESERVATION_PROMO_CODE_DATE_TIME_IN_PAST_OR_FUTURE
          - RESERVATION_PROMO_CODE_INVALID_DAY_OF_WEEK
          - RESERVATION_PROMO_CODE_INVALID_AGENT
          - RESERVATION_PROMO_CODE_INVALID_MERCHANT
          - RESERVATION_PROMO_CODE_INVALID_PARTNER_VOUCHER
          - RESERVATION_PROMO_CODE_ALREADY_OWNED_BY_CUSTOMER
          - RESERVATION_INVITATION_PROMO_CODE_NOT_FIRST_RESERVATION
          - CCV_SETTINGS_REQUIRED
          - CCV_CARD_REQUIRED
          - CCV_SETTINGS_INVALID
          - CCV_SETTINGS_OFFLINE
          - CCV_CARD_INVALID
          - ENQUIRY_INVALID_MIN_COVERS
          - CUSTOMER_FIRST_NAME_INVALID
          - CUSTOMER_LAST_NAME_MISSING
          - CUSTOMER_LAST_NAME_INVALID
          - CUSTOMER_EMAIL_MISSING
          - CUSTOMER_EMAIL_INVALID
          - CUSTOMER_NEWSLETTER_REQUESTED_MISSING
          - CUSTOMER_PHONE_NUMBER_MISSING
          - CUSTOMER_COUNTRY_INVALID
          - CUSTOMER_ID_EXISTS
          - CUSTOMER_PHONE_NUMBER_INVALID
          - UNEXPECTED_SERVER_ERROR
          - PHONE_NUMBER_MISSING
          - PHONE_NUMBER_INVALID
          - UUID_CONFLICT
          - RESERVATION_STATUS_CONFLICT
          - INVALID_RESERVATION_GUESTS_QUANTITY
          - MENU_MAPPING_FAILED
          example: BAD_REQUEST_ERROR
        errorMessage:
          type: string
          example: Window table preferred if available.
    CreateReviewDto:
      type: object
      required:
      - rating
      - reservationId
      properties:
        reservationId:
          type: string
          description: The reservation identifier this review is being created for.Either public reservation identifier or agent specific identifier could be passed.
          example: '88086'
        rating:
          type: integer
          format: int32
          description: 'Possible values: 1 to 6.'
          example: 1
        description:
          type: string
          description: The description of the review.
          example: Window table preferred if available.
    GetReviewDto:
      type: object
      required:
      - rating
      - reviewId
      properties:
        reviewId:
          type: string
          format: uuid
          description: UUID identifying the review.
          example: '88086'
        merchantId:
          type: integer
          format: int32
          description: Merchant Id associated to this review. Only in detailed view.
          example: 88086
        customer:
          description: Data about the customer that made this review. Only in detailed view.
          $ref: '#/components/schemas/CustomerReviewData'
        status:
          type: string
          description: Current review status. Possible values are 'AVAILABLE_TO_REVIEW','CREATED', 'DENIED', 'PUBLISHED'.
          enum:
          - AVAILABLE_TO_REVIEW
          - CREATED
          - DENIED
          - PUBLISHED
          example: AVAILABLE_TO_REVIEW
        locale:
          type: string
          description: Locale of the created review. Only in detailed view.
          example: de_DE
        rating:
          type: integer
          format: int32
          description: 'Rating associated to this review. Possible values: 1 to 6.'
          example: 1
        description:
          type: string
          description: Description associated to this review.
          example: Window table preferred if available.
        reservationId:
          type: string
          description: The reservation identifier this review is created for.
          example: '88086'
        createdAt:
          type: string
          format: date-time
          description: 'The date the review created on. Format: yyyy-MM-ddTHH:mm:ssZ'
          example: '2026-07-15T19:30:00'
  securitySchemes:
    API_TOKEN:
      type: apiKey
      name: X-Quandoo-AuthToken
      in: header
