=== api-evangelist/quandoo/json-schema/quandoo-public-partner-api-reservation-data-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "ReservationData",
  "description": "ReservationData schema from Quandoo Public Partner API",
  "$id": "https://raw.githubusercontent.com/api-evangelist/quandoo/refs/heads/main/json-schema/quandoo-public-partner-api-reservation-data-schema.json",
  "type": "object",
  "required": [
    "capacity",
    "customerId",
    "id",
    "links",
    "merchantId",
    "quandooId",
    "status"
  ],
  "properties": {
    "id": {
      "type": "string",
      "description": "The agent-dependent unique id of the reservation."
    },
    "number": {
      "type": "integer",
      "format": "int32",
      "description": "The id of the reservation on quandoo system."
    },
    "reservationNumber": {
      "type": "string",
      "description": "The long id of this reservation on quandoo system."
    },
    "quandooId": {
      "type": "string",
      "format": "uuid",
      "description": "The public id of this reservation on quandoo system."
    },
    "status": {
      "type": "string",
      "description": "The status of the reservation."
    },
    "updatedAt": {
      "type": "string",
      "format": "date-time",
      "description": "The date the review created on. Format: yyyy-MM-ddTHH:mm:ssZ"
    },
    "capacity": {
      "type": "integer",
      "format": "int32",
      "description": "The capacity of the reservation."
    },
    "merchantId": {
      "type": "integer",
      "format": "int32",
      "description": "The id of the merchant."
    },
    "customerId": {
      "type": "string",
      "description": "The public ID of the customer to which this reservation belongs."
    },
    "promocode": {
      "type": "string",
      "description": "The promotion code used in this reservation. Optional."
    },
    "extraInfo": {
      "type": "string",
      "description": "Extra information that the customer provided for the reservation. Optional."
    },
    "links": {
      "type": "array",
      "description": "The links related to this entity.",
      "items": {
        "type": "object",
        "properties": {
          "href": {
            "type": "string",
            "format": "url"
          },
          "method": {
            "type": "string"
          },
          "rel": {
            "type": "string",
            "enum": [
              "DETAILS",
              "WIDGET",
              "WIDGET_DETAILS",
              "GET_MERCHANT",
              "PARENT",
              "SELF",
              "SETTINGS",
              "AVAILABILITY_DAYS",
              "AVAILABILITIES",
              "CREATE_RESERVATION",
              "GET_RESERVATION",
              "UPDATE_RESERVATION",
              "GET_CUSTOMER_RESERVATION",
              "GET_REVIEW",
              "PORTAL_PREORDER_FORM",
              "RESERVATION_CHECKOUT_PAGE",
              "CREDIT_CARD_DETAILS_PAGE",
              "CUSTOMER_EDIT_RESERVATION"
            ]
          }
        }
      }
    },
    "reservationTags": {
      "type": "array",
      "description": "A list of reservation tag IDs.",
      "items": {
        "type": "integer",
        "format": "int32"
      }
    }
  }
}

=== api-evangelist/quandoo/examples/quandoo-public-partner-api-reservation-data-example.json
{
  "id": "88086",
  "number": 1,
  "reservationNumber": "string",
  "quandooId": "88086",
  "status": "CONFIRMED",
  "updatedAt": "2026-07-15T19:30:00",
  "capacity": 4,
  "merchantId": 88086,
  "customerId": "88086",
  "promocode": "string",
  "extraInfo": "Window table preferred if available.",
  "links": [
    {
      "href": "https://www.quandoo.com/place/sample-restaurant",
      "method": "string",
      "rel": "DETAILS"
    }
  ],
  "reservationTags": [
    1
  ]
}
