=== api-evangelist/quandoo/json-schema/quandoo-public-partner-api-merchant-reservation-settings-dto-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "MerchantReservationSettingsDto",
  "description": "MerchantReservationSettingsDto schema from Quandoo Public Partner API",
  "$id": "https://raw.githubusercontent.com/api-evangelist/quandoo/refs/heads/main/json-schema/quandoo-public-partner-api-merchant-reservation-settings-dto-schema.json",
  "type": "object",
  "properties": {
    "areaIds": {
      "type": "array",
      "description": "List of all the areas defined for the merchant. Each area will contain:",
      "items": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "format": "int32",
            "description": "Id of the area"
          },
          "name": {
            "type": "string",
            "description": "Name of the area"
          },
          "priority": {
            "type": "integer",
            "format": "int32",
            "description": "Priority set for this area"
          }
        }
      }
    },
    "capacities": {
      "type": "array",
      "description": "Number of guests allowed in a reservation",
      "items": {
        "type": "integer",
        "format": "int32"
      }
    },
    "merchantNewsletterSelectionRequired": {
      "type": "boolean",
      "description": "If true, a separate checkbox is displayed in the checkout for newsletter received from the restaurant"
    },
    "areaSelectionRequired": {
      "type": "boolean",
      "description": "If true, we display available areas in a dropdown when a guest is making an online reservation"
    },
    "reservationEnquiryEnabled": {
      "type": "boolean",
      "description": "If true, the restaurants allows enquiries"
    },
    "minimumCapacityForEnquiries": {
      "type": "integer",
      "format": "int32",
      "description": "Minimum number of guests for an enquiry"
    },
    "onlineReservationInterval": {
      "type": "integer",
      "format": "int32",
      "description": "Time slots displayed for making a reservation"
    },
    "specialTerms": {
      "type": "string",
      "description": "If true, special terms and conditions of the restaurant need to be confirmed upon making an online reservation"
    },
    "links": {
      "type": "array",
      "description": "Related links that can be followed based on this response",
      "items": {
        "type": "object",
        "properties": {
          "href": {
            "type": "string",
            "format": "url"
          },
          "method": {
            "type": "string"
          },
          "rel": {
            "type": "string",
            "enum": [
              "DETAILS",
              "WIDGET",
              "WIDGET_DETAILS",
              "GET_MERCHANT",
              "PARENT",
              "SELF",
              "SETTINGS",
              "AVAILABILITY_DAYS",
              "AVAILABILITIES",
              "CREATE_RESERVATION",
              "GET_RESERVATION",
              "UPDATE_RESERVATION",
              "GET_CUSTOMER_RESERVATION",
              "GET_REVIEW",
              "PORTAL_PREORDER_FORM",
              "RESERVATION_CHECKOUT_PAGE",
              "CREDIT_CARD_DETAILS_PAGE",
              "CUSTOMER_EDIT_RESERVATION"
            ]
          }
        }
      }
    },
    "automaticConfirmation": {
      "type": "boolean",
      "description": "If true, the customer will receive an automatic email confirmation after he makes a reservation"
    },
    "ccvEnabled": {
      "type": "boolean",
      "description": "If true, credit card information is required when creating a reservation"
    }
  }
}

=== api-evangelist/quandoo/examples/quandoo-public-partner-api-merchant-reservation-settings-dto-example.json
{
  "areaIds": [
    {
      "id": 1,
      "name": "Sample Restaurant",
      "priority": 1
    }
  ],
  "capacities": [
    1
  ],
  "merchantNewsletterSelectionRequired": true,
  "areaSelectionRequired": true,
  "reservationEnquiryEnabled": true,
  "minimumCapacityForEnquiries": 4,
  "onlineReservationInterval": 1,
  "specialTerms": "string",
  "links": [
    {
      "href": "https://www.quandoo.com/place/sample-restaurant",
      "method": "string",
      "rel": "DETAILS"
    }
  ],
  "automaticConfirmation": true,
  "ccvEnabled": true
}
